/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user and org for this API key */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List prospects already in this org (from connected CRM/warehouse snapshots). Do not cache PII locally. */
        get: operations["listProspects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prospects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one prospect by id */
        get: operations["getProspect"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces for this org */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tools/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Materialize a workspace from a prompt (hydrates contacts from the connected CRM/warehouse) */
        post: operations["deployTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a workspace (not the full UI bundle) */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List contacts in a workspace */
        get: operations["listContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/queue/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next actionable contact plus current step template */
        get: operations["queueNext"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send email or LinkedIn (or save a draft) */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{id}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start a dial session for a contact */
        post: operations["startCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calls/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete an open call with a disposition */
        post: operations["completeCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{id}/disposition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log an outcome without an open call */
        post: operations["disposition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Append a note to a contact */
        post: operations["addNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
            code?: string;
        };
        /** @enum {string} */
        ContactStatus: "queued" | "active" | "completed" | "replied" | "no_answer" | "interested" | "not_interested";
        /** @enum {string} */
        ProjectKind: "dialer" | "sequencer" | "cadence" | "list" | "today" | "generic";
        User: {
            id: string;
            email: string;
            name: string;
        };
        Org: {
            id: string;
            name: string;
            slug: string;
        };
        Me: {
            user: components["schemas"]["User"];
            org: components["schemas"]["Org"];
            /** @enum {string} */
            environment: "live" | "sandbox";
            outbound: {
                /** @enum {string} */
                email: "live" | "demo" | "sandbox";
                /** @enum {string} */
                voice: "live" | "demo" | "sandbox";
                /** @enum {string} */
                linkedin: "live" | "demo" | "sandbox";
            };
        };
        Project: {
            id: string;
            name: string;
            kind: components["schemas"]["ProjectKind"];
            prompt: string;
            segment?: string;
            description?: string;
            contactCount: number;
            /** @description Path on jargonlabs.co, e.g. /tools/{id} */
            dashboardPath: string;
            createdAt: number;
            updatedAt: number;
        };
        DeployRequest: {
            prompt: string;
        };
        DeployResult: {
            projectId: string;
            contactCount: number;
            dashboardPath: string;
            project: components["schemas"]["Project"];
        };
        Contact: {
            id: string;
            projectId: string;
            name: string;
            company: string;
            title: string;
            email: string;
            phone: string;
            city?: string;
            status: components["schemas"]["ContactStatus"];
            stepIndex: number;
            notes?: string;
            linkedinUrl?: string;
            accountName?: string;
            context?: string[];
            createdAt?: number;
            updatedAt?: number;
        };
        ContactList: {
            contacts: components["schemas"]["Contact"][];
            total: number;
            limit: number;
            offset: number;
        };
        Step: {
            id: string;
            day?: number;
            /** @enum {string} */
            channel: "email" | "call" | "linkedin";
            label: string;
            subject?: string;
            body?: string;
            order: number;
        };
        QueueNext: {
            contact: components["schemas"]["Contact"] | null;
            step: components["schemas"]["Step"] | null;
            remaining: number;
        };
        SendMessageRequest: {
            /**
             * @default email
             * @enum {string}
             */
            channel: "email" | "linkedin";
            /**
             * @default sent
             * @enum {string}
             */
            status: "draft" | "queued" | "sent";
            subject?: string;
            body: string;
        };
        Message: {
            id: string;
            contactId: string;
            projectId: string;
            /** @enum {string} */
            channel: "email" | "linkedin";
            /** @enum {string} */
            status: "draft" | "queued" | "sent" | "failed";
            subject?: string;
            body: string;
            /** @enum {string} */
            mode?: "demo" | "gmail" | "heyreach";
            createdAt?: number;
            sentAt?: number;
        };
        Call: {
            id: string;
            contactId: string;
            projectId: string;
            /** @enum {string} */
            phase: "dialing" | "ringing" | "connected" | "completed" | "failed";
            disposition?: components["schemas"]["ContactStatus"];
            /** @enum {string} */
            mode: "demo" | "twilio";
            startedAt: number;
            connectedAt?: number;
            endedAt?: number;
        };
        DispositionRequest: {
            status: components["schemas"]["ContactStatus"];
            note?: string;
            advanceStep?: boolean;
        };
    };
    responses: {
        /** @description Missing or non-API-key bearer token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not found in this org */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many send or dial requests in the current 15-minute window */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: string;
        /** @description Required on dial/send. Replay within 24h returns the original response (Idempotent-Replay: true). */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listProspects: {
        parameters: {
            query?: {
                /** @description Limit to one workspace */
                projectId?: string;
                status?: components["schemas"]["ContactStatus"];
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactList"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getProspect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contact"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: components["schemas"]["Project"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deployTool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["Error"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listContacts: {
        parameters: {
            query?: {
                status?: components["schemas"]["ContactStatus"];
                /** @description Search name, company, title, email, city */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactList"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    queueNext: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK — contact may be null when the queue is empty */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueNext"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on dial/send. Replay within 24h returns the original response (Idempotent-Replay: true). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message: components["schemas"]["Message"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
            502: components["responses"]["Error"];
        };
    };
    startCall: {
        parameters: {
            query?: never;
            header: {
                /** @description Required on dial/send. Replay within 24h returns the original response (Idempotent-Replay: true). */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        call: components["schemas"]["Call"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["Error"];
            429: components["responses"]["RateLimited"];
        };
    };
    completeCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    disposition: components["schemas"]["ContactStatus"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        call: components["schemas"]["Call"];
                        next: components["schemas"]["QueueNext"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    disposition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DispositionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contact: components["schemas"]["Contact"];
                        next: components["schemas"]["QueueNext"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    addNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    note: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        contact: components["schemas"]["Contact"];
                    };
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
